In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
from sklearn.neighbors import KNeighborsClassifier

In [3]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

In [4]:
data = pd.read_csv("FitBit data.csv")
print(data.head(10))

           Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
0  1503960366    3/25/2016       11004           7.11             7.11   
1  1503960366    3/26/2016       17609          11.55            11.55   
2  1503960366    3/27/2016       12736           8.53             8.53   
3  1503960366    3/28/2016       13231           8.93             8.93   
4  1503960366    3/29/2016       12041           7.85             7.85   
5  1503960366    3/30/2016       10970           7.16             7.16   
6  1503960366    3/31/2016       12256           7.86             7.86   
7  1503960366     4/1/2016       12262           7.87             7.87   
8  1503960366     4/2/2016       11248           7.25             7.25   
9  1503960366     4/3/2016       10016           6.37             6.37   

   LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                       0.0                2.57                      0.46   
1                       0.0    

In [5]:
print(data.isnull().sum())

Id                          0
ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64


In [6]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Id                        457 non-null    int64  
 1   ActivityDate              457 non-null    object 
 2   TotalSteps                457 non-null    int64  
 3   TotalDistance             457 non-null    float64
 4   TrackerDistance           457 non-null    float64
 5   LoggedActivitiesDistance  457 non-null    float64
 6   VeryActiveDistance        457 non-null    float64
 7   ModeratelyActiveDistance  457 non-null    float64
 8   LightActiveDistance       457 non-null    float64
 9   SedentaryActiveDistance   457 non-null    float64
 10  VeryActiveMinutes         457 non-null    int64  
 11  FairlyActiveMinutes       457 non-null    int64  
 12  LightlyActiveMinutes      457 non-null    int64  
 13  SedentaryMinutes          457 non-null    int64  
 14  Calories  

In [7]:
print(data.describe())

                 Id    TotalSteps  TotalDistance  TrackerDistance  \
count  4.570000e+02    457.000000     457.000000       457.000000   
mean   4.628595e+09   6546.562363       4.663523         4.609847   
std    2.293781e+09   5398.493064       4.082072         4.068540   
min    1.503960e+09      0.000000       0.000000         0.000000   
25%    2.347168e+09   1988.000000       1.410000         1.280000   
50%    4.057193e+09   5986.000000       4.090000         4.090000   
75%    6.391747e+09  10198.000000       7.160000         7.110000   
max    8.877689e+09  28497.000000      27.530001        27.530001   

       LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
count                457.000000          457.000000                457.000000   
mean                   0.179427            1.180897                  0.478643   
std                    0.849232            2.487159                  0.830995   
min                    0.000000            0.000000   

In [8]:
data["ActivityDate"] = pd.to_datetime(data["ActivityDate"],format="%m/%d/%Y")

In [9]:
X = data.drop(columns=['Id', 'ActivityDate'])
y = data['ActivityDate']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [12]:
KNN = KNeighborsClassifier()

In [13]:
KNN.fit(X_train, y_train)

KNeighborsClassifier()

In [14]:
knn_pred = KNN.predict(X_test)

c:\Users\SaiAnkith\anaconda3\anaconda\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [15]:
knn_pred

array(['2016-04-01T00:00:00.000000000', '2016-04-08T00:00:00.000000000',
       '2016-04-04T00:00:00.000000000', '2016-03-17T00:00:00.000000000',
       '2016-04-05T00:00:00.000000000', '2016-03-23T00:00:00.000000000',
       '2016-03-21T00:00:00.000000000', '2016-04-04T00:00:00.000000000',
       '2016-04-05T00:00:00.000000000', '2016-03-26T00:00:00.000000000',
       '2016-04-08T00:00:00.000000000', '2016-03-29T00:00:00.000000000',
       '2016-03-29T00:00:00.000000000', '2016-04-01T00:00:00.000000000',
       '2016-04-05T00:00:00.000000000', '2016-04-01T00:00:00.000000000',
       '2016-04-01T00:00:00.000000000', '2016-04-06T00:00:00.000000000',
       '2016-04-01T00:00:00.000000000', '2016-04-02T00:00:00.000000000',
       '2016-03-28T00:00:00.000000000', '2016-04-01T00:00:00.000000000',
       '2016-03-22T00:00:00.000000000', '2016-04-02T00:00:00.000000000',
       '2016-03-17T00:00:00.000000000', '2016-04-01T00:00:00.000000000',
       '2016-03-28T00:00:00.000000000', '2016-04-01

In [16]:
knn_cm = confusion_matrix(y_test, knn_pred)
print(knn_cm)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 

In [17]:
print(f1_score(y_test, knn_pred, average = 'weighted'))

0.05463386727688787


In [18]:
print("KNN Accuracy:", accuracy_score(y_test, knn_pred))

KNN Accuracy: 0.05434782608695652


In [19]:
print("\nClassification Report - KNN:")
print(classification_report(y_test, knn_pred))


Classification Report - KNN:
                               precision    recall  f1-score   support

2016-03-13T00:00:00.000000000       0.00      0.00      0.00         0
2016-03-14T00:00:00.000000000       0.00      0.00      0.00         1
2016-03-15T00:00:00.000000000       0.00      0.00      0.00         1
2016-03-17T00:00:00.000000000       0.00      0.00      0.00         0
2016-03-18T00:00:00.000000000       0.00      0.00      0.00         1
2016-03-19T00:00:00.000000000       0.00      0.00      0.00         1
2016-03-21T00:00:00.000000000       0.00      0.00      0.00         0
2016-03-22T00:00:00.000000000       0.00      0.00      0.00         0
2016-03-23T00:00:00.000000000       0.00      0.00      0.00         0
2016-03-24T00:00:00.000000000       0.00      0.00      0.00         1
2016-03-25T00:00:00.000000000       0.00      0.00      0.00         2
2016-03-26T00:00:00.000000000       0.00      0.00      0.00         0
2016-03-27T00:00:00.000000000       0.00      

c:\Users\SaiAnkith\anaconda3\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\SaiAnkith\anaconda3\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\SaiAnkith\anaconda3\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\SaiAnkith\anaco